name: tree

on:
  push:
    branches:
    - master
    tags:
    - '!*'
  pull_request:

jobs:

  build:
    name: tree

    strategy:
      matrix:
        os: [darwin/x86_64, linux/x86_64]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build --tag build dockerfiles/tree/${{ matrix.os }}

    - name: Copy `tree` to host
      run: docker run --rm -v "$(pwd)"/out:/out build cp -v tree /out

    - uses: actions/upload-artifact@v2
      with:
        name: tree
        path: out/*
